import { Open_Sans } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./providers/NextAuthProvider";


const openSans = Open_Sans ({
  variable:'--font-openSans',
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Digital Wallet",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased`}
      >
        
         <NextAuthProvider>
           {children}
         </NextAuthProvider>
        
      </body>
    </html>
  );
}
