import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterSection from "./components/shared/Footer";
import { Wallet } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Digital Wallet",
  description: "Generated by create next app",
   icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar /> */}
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
